### ISSUE TITLE
Link resolving not working with Model 2.0.3

### ISSUE THREAD

**Issue by saurabhmca0710** [sdl/dxa-model-service#11]
Dynamic link resolving was working fine till 2.0.2.
As soon as we upgraded to Model 2.0.3 service, link resolving stopped working.

**Comment by rpannekoek** [comment]
Please contact SDL Customer Support to get this analyzed/fixed.

**Comment by rpannekoek** [comment]
This issue has too little information in what "link resolving stopped working" means exactly.  AFAIK, SDL Customer Support has not been contacted either.
For now assuming it is a similar issue as https://github.com/sdl/dxa-model-service/issues/12

Internal Issue ID: CRQ-15566

**Comment by alebastrov** [comment]
outdated
