### ISSUE TITLE
Empty KeywordModelData when retriving a dynamic component presentation

### ISSUE THREAD

**Issue by tfinez** [sdl/dxa-model-service#2]
Using DXA 2.0 + SDL Web 8.5, when we try to retrieve the keywords from a component that it's linked to a dynamic component presentation, the keyword info is not populated. The keyword is published, and in fact we need this category to be publishable.

When the component is linked to a page, the KeywordDataModel is rightly populated.

**Comment by tfinez** [comment]
The problem is that in the class ContentService, the function _loadComponentPresentation_ is not returning the keywordDataModel for a publishable Category when launching the query:

componentPresentation = componentPresentationFactory.getComponentPresentation(publicationId, componentId, templateId);

**Comment by oleksii-kondratiuk** [comment]
Thank you for reporting this issue. SDL engineering team is looking into it.

**Comment by dmandava** [comment]
We are facing the same issue with empty KeywordModelData. Can you'll provide an ETA on when this fix will be available in DXA 2.0?

**Comment by Vouzamo** [comment]
+1 - This is a high priority item for us too.

**Comment by rpannekoek** [comment]
This issue has been fixed (hotfix can be obtained from SDL Customer Support). The hotfix will soon be released on GitHub.

**Comment by rpannekoek** [comment]
Internal Issue ID (for tracking purposes): CRQ-10511

**Comment by rpannekoek** [comment]
The fix for this issue is incorporated in the DXA 2.1 code base and also in the a [DXA Model Service v2.0.1 hotfix release](https://github.com/sdl/dxa-model-service/releases/tag/DXA_2.0.1_Hotfix).
